DROP DATABASE IF EXISTS @DATABASE@;
create database @DATABASE@;

#user @USERPHPBB@
GRANT USAGE ON *.* TO '@USERPHPBB@'@'@HOSTNAME@';
DROP USER '@USERPHPBB@'@'@HOSTNAME@';
CREATE USER '@USERPHPBB@'@'@HOSTNAME@' IDENTIFIED BY '@PASSPHPBB@';

GRANT ALL PRIVILEGES ON * . * TO '@USERPHPBB@'@'@HOSTNAME@' IDENTIFIED BY '@PASSPHPBB@' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

GRANT ALL PRIVILEGES ON `@USERPHPBB@\_%` . * TO '@USERPHPBB@'@'@HOSTNAME@';

GRANT USAGE ON *.* TO '@USERPHPBB@'@'localhost';

DROP USER '@USERPHPBB@'@'localhost';

CREATE USER '@USERPHPBB@'@'localhost' IDENTIFIED BY '@PASSPHPBB@';

GRANT ALL PRIVILEGES ON * . * TO '@USERPHPBB@'@'localhost' IDENTIFIED BY '@PASSPHPBB@' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

GRANT ALL PRIVILEGES ON `@USERPHPBB@\_%` . * TO '@USERPHPBB@'@'localhost';
FLUSH PRIVILEGES;


