<?php
// Automatically Generated by TestLink Installer
define('DB_TYPE', 'mysql');
define('DB_USER', '@TESTLINK_USER@');
define('DB_PASS', '@TESTLINK_PWD@');
define('DB_HOST', '@MARIADB_HOST@');
define('DB_NAME', '@DATABASE@');
define('DB_TABLE_PREFIX', '');
?>
