DROP DATABASE IF EXISTS `@DATABASE@`;
CREATE DATABASE `@DATABASE@`;

#user sympa 
GRANT USAGE ON *.* TO '@SYMPA_DB_USER@'@'@MARIADB_HOST@'; 
DROP USER '@SYMPA_DB_USER@'@'@MARIADB_HOST@'; 
CREATE USER '@SYMPA_DB_USER@'@'@MARIADB_HOST@' IDENTIFIED BY '@SYMPA_DB_PWD@'; 
 
GRANT ALL PRIVILEGES ON * . * TO '@SYMPA_DB_USER@'@'@MARIADB_HOST@' IDENTIFIED BY '@SYMPA_DB_PWD@' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ; 
 
GRANT ALL PRIVILEGES ON `sympa\_%` . * TO '@SYMPA_DB_USER@'@'@MARIADB_HOST@'; 
 
GRANT USAGE ON *.* TO '@SYMPA_DB_USER@'@'localhost'; 
 
DROP USER '@SYMPA_DB_USER@'@'localhost'; 
 
CREATE USER '@SYMPA_DB_USER@'@'localhost' IDENTIFIED BY '@SYMPA_DB_PWD@'; 
 
GRANT ALL PRIVILEGES ON * . * TO '@SYMPA_DB_USER@'@'localhost' IDENTIFIED BY '@SYMPA_DB_PWD@' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ; 
 
GRANT ALL PRIVILEGES ON `sympa\_%` . * TO '@SYMPA_DB_USER@'@'localhost'; 
FLUSH PRIVILEGES; 