DROP DATABASE IF EXISTS `sonar`;
CREATE DATABASE `sonar`;
GRANT ALL ON `sonar`.* TO '@SONAR_USER@'@'@MARIADB_HOST@' IDENTIFIED BY '@SONAR_PWD@' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
