DROP DATABASE IF EXISTS %DATABASE%;
create database %DATABASE%;

#user %USERMANTIS%
GRANT USAGE ON *.* TO '%USERMANTIS%'@'%HOSTNAME%';
DROP USER '%USERMANTIS%'@'%HOSTNAME%';
CREATE USER '%USERMANTIS%'@'%HOSTNAME%' IDENTIFIED BY '%PASSMANTIS%';

GRANT ALL PRIVILEGES ON * . * TO '%USERMANTIS%'@'%HOSTNAME%' IDENTIFIED BY '%PASSMANTIS%' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

GRANT ALL PRIVILEGES ON `%USERMANTIS%\_%` . * TO '%USERMANTIS%'@'%HOSTNAME%';

GRANT USAGE ON *.* TO '%USERMANTIS%'@'localhost';

DROP USER '%USERMANTIS%'@'localhost';

CREATE USER '%USERMANTIS%'@'localhost' IDENTIFIED BY '%PASSMANTIS%';

GRANT ALL PRIVILEGES ON * . * TO '%USERMANTIS%'@'localhost' IDENTIFIED BY '%PASSMANTIS%' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

GRANT ALL PRIVILEGES ON `%USERMANTIS%\_%` . * TO '%USERMANTIS%'@'localhost';
FLUSH PRIVILEGES;

