<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin1
 * Date: Fri, 02 Aug 2013 11:09:55 +0200
 */

$conf['title'] = 'Dokuwiki';
$conf['lang'] = 'fr';
$conf['license'] = 'gnufdl';
$conf['updatecheck'] = 0;
$conf['savedir'] = '@DATA_DIR@';
