DROP DATABASE IF EXISTS `@DATABASE@`;
CREATE USER '@SPIP_USER@'@'@MARIADB_HOST@' IDENTIFIED BY  '@SPIP_PWD@';
CREATE DATABASE  `@DATABASE@`;
GRANT ALL PRIVILEGES ON * . *  TO '@SPIP_USER@'@'@MARIADB_HOST@' WITH GRANT OPTION ;
